version: '3.8'

services:
  # --- Service 1: Task Manager Application ---
  task-manager:
    container_name: running-app
    image: task-manger-app
    # Note: We removed the public "ports:" flag array! The app is now protected
    # inside the private container network, accessible only through Nginx.
    volumes:
      - ./my-new-app/backend:/app/backend
    restart: always

  # # --- Service 2: Server Monitor Application ---
  # server-monitor:
  #   container_name: running-monitor
  #   image: server-monitor-app
  #   volumes:
  #     - ./server-monitor-app/backend:/app/backend
  #   restart: always
  
    # --- Service 2: Server Monitor Application ---
  server-monitor:
    container_name: running-monitor
    # Update these lines to force Docker to read your local folder files directly:
    build:
      context: ./server-monitor-app
      dockerfile: Dockerfile
    volumes:
      - ./server-monitor-app/backend:/app/backend
    restart: always


    # --- Service 3: Nginx Gateway Reverse Proxy ---
  reverse-proxy:
    container_name: running-proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Add these two new lines below to pass your frontends to Nginx:
      - ./my-new-app/frontend:/usr/share/nginx/html/tasks:ro
      - ./server-monitor-app/frontend:/usr/share/nginx/html/monitor:ro
    depends_on:
      - task-manager
      - server-monitor
    restart: always

