server {
    listen 80;
    server_name localhost;

    # Route Task Manager network traffic to port 5000 internally
    location /api/tasks {
        proxy_pass http://task-manager:5000/api/tasks;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route Server Monitor network traffic to port 4000 internally
    location /api/logs {
        proxy_pass http://server-monitor:4000/api/logs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
